Fixed maximum recursion issue of test_linalg.py (#2713)
test_linalg.py tests fail with the following due to missing IFU from
commit
https://github.com/pytorch/pytorch/commit/cd949d133e2ae5de47e860d2d2350cbfbd18fe20
Traceback (most recent call last):
File "/var/lib/jenkins/pytorch/test/test_linalg.py", line 112, in setUp
    super(self.__class__, self).setUp()
File "/var/lib/jenkins/pytorch/test/test_linalg.py", line 112, in setUp
    super(self.__class__, self).setUp()
File "/var/lib/jenkins/pytorch/test/test_linalg.py", line 112, in setUp
    super(self.__class__, self).setUp()
  [Previous line repeated 982 more times]
RecursionError: maximum recursion depth exceeded